# Generated by Django 5.2.15 on 2026-07-02 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Glaze",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cone", models.CharField(max_length=20)),
                ("color", models.CharField(default="Unknown", max_length=50)),
                ("surface", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ingredient_type", models.CharField(blank=True, max_length=50)),
                ("safety_notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="GlazeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("unit", models.CharField(default="percent", max_length=20)),
                ("is_additive", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "glaze",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.glaze"
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ingredient",
                    ),
                ),
            ],
        ),
    ]
