# Generated by Django 5.2.15 on 2026-07-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="glazeingredient",
            name="glaze",
        ),
        migrations.RemoveField(
            model_name="glazeingredient",
            name="ingredient",
        ),
        migrations.DeleteModel(
            name="Glaze",
        ),
        migrations.DeleteModel(
            name="GlazeIngredient",
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
