# Generated by Django 5.2.15 on 2026-07-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="glazeingredient",
            name="is_additive",
        ),
        migrations.RemoveField(
            model_name="glazeingredient",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="ingredient_type",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="safety_notes",
        ),
    ]
