# Generated by Django 5.2.15 on 2026-07-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_glazeingredient_is_additive_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="glaze",
            old_name="surface",
            new_name="texture",
        ),
        migrations.AddField(
            model_name="glaze",
            name="transparency",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
