# Generated by Django 5.2.15 on 2026-07-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_surface_glaze_texture_glaze_transparency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glaze",
            name="texture",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("Glossy", "Glossy"),
                    ("Matte", "Matte"),
                    ("Satin", "Satin"),
                ],
                default="Unknown",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="glaze",
            name="transparency",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("Opaque", "Opaque"),
                    ("Semi-translucent", "Semi-translucent"),
                    ("Translucent", "Translucent"),
                ],
                default="Unknown",
                max_length=50,
            ),
        ),
    ]
