# Generated by Django 5.2.15 on 2026-07-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_glaze_texture_alter_glaze_transparency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glaze",
            name="cone",
            field=models.CharField(
                choices=[("04", "04"), ("6", "6"), ("7", "7"), ("10", "10")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="glaze",
            name="texture",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("Glossy", "Glossy"),
                    ("Matte", "Matte"),
                    ("Satin", "Satin"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="glaze",
            name="transparency",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("Opaque", "Opaque"),
                    ("Semi-translucent", "Semi-translucent"),
                    ("Translucent", "Translucent"),
                ],
                max_length=50,
            ),
        ),
    ]
