# Generated by Django 5.2.15 on 2026-07-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_glaze_cone_alter_glaze_texture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="glaze",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="glaze_images/"),
        ),
    ]
