# Generated by Django 5.2.16 on 2026-08-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_glaze_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlazePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="glaze_images/")),
                (
                    "glaze",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.glaze",
                    ),
                ),
            ],
        ),
    ]
