# Generated by Django 5.2.16 on 2026-08-13 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_glazephoto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="glazeingredient",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="glaze",
            name="color",
        ),
        migrations.RemoveField(
            model_name="glaze",
            name="image",
        ),
        migrations.RemoveField(
            model_name="glazeingredient",
            name="unit",
        ),
        migrations.AddField(
            model_name="glazeingredient",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="glazephoto",
            name="caption",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="glaze",
            name="cone",
            field=models.CharField(
                choices=[
                    ("04", "Cone 04"),
                    ("6", "Cone 6"),
                    ("7", "Cone 7"),
                    ("10", "Cone 10"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="glaze",
            name="texture",
            field=models.CharField(
                choices=[("Glossy", "Glossy"), ("Matte", "Matte"), ("Satin", "Satin")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="glaze",
            name="transparency",
            field=models.CharField(
                choices=[
                    ("Opaque", "Opaque"),
                    ("Semi-translucent", "Semi-translucent"),
                    ("Translucent", "Translucent"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="glazeingredient",
            name="amount",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="glazeingredient",
            name="glaze",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="core.glaze",
            ),
        ),
        migrations.AlterField(
            model_name="glazephoto",
            name="image",
            field=models.ImageField(upload_to="glaze_photos/"),
        ),
        migrations.CreateModel(
            name="GlazeVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "glaze",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.glaze",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariantAdditive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.CharField(max_length=50)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additives",
                        to="core.glazevariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariantPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="variant_photos/")),
                ("caption", models.CharField(blank=True, max_length=100)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.glazevariant",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
